//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersManufactor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCostHistory
    {
        public double ID { get; set; }
        public string ProductID { get; set; }
        public string ChangeDate { get; set; }
        public string CostValue { get; set; }
    }
}
